using System;
using System.Collections.Generic;
using CrowdControl.Common;
using CrowdControl.Games.Packs;
using ConnectorType = CrowdControl.Common.ConnectorType;

public class Minecraft : SimpleTCPPack
{
    public override string Host => "127.0.0.1";

    public override ushort Port => 58431;

    public Minecraft(IPlayer player, Func<CrowdControlBlock, bool> responseHandler, Action<object> statusUpdateHandler) : base(player, responseHandler, statusUpdateHandler) { }

    public override Game Game => new Game(108, "Minecraft (Server)", "minecraftserver", "PC", ConnectorType.SimpleTCPConnector);

    public override List<Effect> Effects => new List<Effect>
    {
        // miscellaneous
        new Effect("Spawn Ore Vein", "vein"),
        new Effect("Spooky Sound Effect", "sfx"),
        new Effect("Swap Locations", "swap"), // swaps the locations of every online player
        new Effect("Dinnerbone", "dinnerbone"), // flips nearby mobs upside-down
        new Effect("Clutter Inventories", "clutter"), // shuffles around a couple items in everyone's inventory
        new Effect("Open Lootbox", "lootbox"), // gives a completely random item with varying enchants and modifiers
        new Effect("Eat Chorus Fruit", "chorus_fruit"), // teleports the player to a random nearby block as if they ate a Chorus Fruit
        new Effect("Render Toasts", "toast"), // displays a bunch of "Recipe Unlocked" notifications in the top right
        new Effect("Freeze", "freeze"), // locks everyone in place for 7 seconds (camera rotation allowed)
        new Effect("Camera Lock", "camera_lock"), // locks everyone's camera in place for 7 seconds (movement allowed)
        new Effect("Place Flowers", "flowers"), // places a bunch of flowers nearby as if a Bonemeal item was used
        new Effect("Place Torches", "lit"), // places torches on every valid nearby block
        new Effect("Remove Torches", "dim"), // removes nearby torches
        new Effect("Replace Area With Gravel", "gravel_hell"), // replaces nearby stone blocks with gravel
        new Effect("Dig Hole", "dig"), // creates a small hole underneath every player
        new Effect("Zip Time", "zip"), // adds a minute to the in-game day/night cycle
        new Effect("Name Item", "name_item"), // names a held item after the viewer
        new Effect("Repair Item", "repair_item"), // sets the durability of an item to 100%
        new Effect("Damage Item", "damage_item"), // sets the durability of an item to 50%
        new Effect("Put Item on Head", "hat"), // swaps the held item and the player's head item
        new Effect("Respawn Players", "respawn"),
        new Effect("Drop Held Item", "drop_item"),
        new Effect("Delete Held Item", "delete_item"),
        new Effect("Water Bucket Clutch", "bucket_clutch"), // teleports players 30 blocks up and gives them a water bucket
        new Effect("Kill Players", "kill"),
        new Effect("Damage Players (1 Heart)", "damage_1"),
        new Effect("Heal Players (1 Heart)", "heal_1"),
        new Effect("Heal Players", "full_heal"),
        new Effect("Feed Players", "feed"),
        new Effect("Feed Players (1 Bar)", "feed_1"),
        new Effect("Starve Players", "starve"),
        new Effect("Remove One Hunger Bar", "starve_1"),
        new Effect("Give One XP Level", "xp_plus1"),
        new Effect("Take One XP Level", "xp_sub1"),
        new Effect("Reset Experience Progress", "reset_exp_progress"),
        new Effect("+1 Max Health", "max_health_plus1"),
        new Effect("-1 Max Health", "max_health_sub1"),
        new Effect("Disable Jumping", "disable_jumping"),
        // teleports players by a few blocks in the specified direction
        new Effect("Move Up", "up"),
        new Effect("Move Down", "down"),
        new Effect("Move X+", "xplus"),
        new Effect("Move X-", "xminus"),
        new Effect("Move Z+", "zplus"),
        new Effect("Move Z-", "zminus"),
        // summons a mob around each player
        new Effect("Summon Charged Creeper", "entity_charged_creeper"),
        new Effect("Summon Creeper", "entity_creeper"),
        new Effect("Summon Skeleton", "entity_skeleton"),
        new Effect("Summon Zombie", "entity_zombie"),
        new Effect("Summon Zoglin", "entity_zoglin"),
        new Effect("Summon Bat", "entity_bat"),
        new Effect("Summon Bee", "entity_bee"),
        new Effect("Summon Blaze", "entity_blaze"),
        new Effect("Summon Boat", "entity_boat"),
        new Effect("Summon Cat", "entity_cat"),
        new Effect("Summon Cave Spider", "entity_cave_spider"),
        new Effect("Summon Cod", "entity_cod"),
        new Effect("Summon Cow", "entity_cow"),
        new Effect("Summon Chicken", "entity_chicken"),
        new Effect("Summon Dolphin", "entity_dolphin"),
        new Effect("Summon Donkey", "entity_donkey"),
        new Effect("Summon Drowned", "entity_drowned"),
        new Effect("Summon Elder Guardian", "entity_elder_guardian"),
        new Effect("Summon Enderman", "entity_enderman"),
        new Effect("Summon Endermite", "entity_endermite"),
        new Effect("Summon Evoker", "entity_evoker"),
        new Effect("Summon Fox", "entity_fox"),
        new Effect("Summon Ghast", "entity_ghast"),
        new Effect("Summon Giant", "entity_giant"),
        new Effect("Summon Guardian", "entity_guardian"),
        new Effect("Summon Hoglin", "entity_hoglin"),
        new Effect("Summon Horse", "entity_horse"),
        new Effect("Summon Husk", "entity_husk"),
        new Effect("Summon Lightning Bolt", "entity_lightning"),
        new Effect("Summon Iron Golem", "entity_iron_golem"),
        new Effect("Summon Illusioner", "entity_illusioner"),
        new Effect("Summon Llama", "entity_llama"),
        new Effect("Summon Magma Cube", "entity_magma_cube"),
        new Effect("Summon Minecart", "entity_minecart"),
        new Effect("Summon Minecart with Chest", "entity_minecart_chest"),
        new Effect("Summon Minecart with Furnace", "entity_minecart_furnace"),
        new Effect("Summon Minecart with Hopper", "entity_minecart_hopper"),
        new Effect("Summon Minecart with TNT", "entity_minecart_tnt"),
        new Effect("Summon Primed TNT", "entity_primed_tnt"),
        new Effect("Summon Mule", "entity_mule"),
        new Effect("Summon Mooshroom", "entity_mushroom_cow"),
        new Effect("Summon Ocelot", "entity_ocelot"),
        new Effect("Summon Panda", "entity_panda"),
        new Effect("Summon Parrot", "entity_parrot"),
        new Effect("Summon Phantom", "entity_phantom"),
        new Effect("Summon Pig", "entity_pig"),
        new Effect("Summon Piglin", "entity_piglin"),
        new Effect("Summon Piglin Brute", "entity_piglin_brute"),
        new Effect("Summon Pillager", "entity_pillager"),
        new Effect("Summon Polar Bear", "entity_polar_bear"),
        new Effect("Summon Pufferfish", "entity_pufferfish"),
        new Effect("Summon Zombified Piglin", "entity_zombified_piglin"),
        new Effect("Summon Zombie Horse", "entity_zombie_horse"),
        new Effect("Summon Zombie Villager", "entity_zombie_villager"),
        new Effect("Summon Wolf", "entity_wolf"),
        new Effect("Summon Wither Skeleton", "entity_wither_skeleton"),
        new Effect("Summon Wandering Trader", "entity_wandering_trader"),
        new Effect("Summon Witch", "entity_witch"),
        new Effect("Summon Vindicator", "entity_vindicator"),
        new Effect("Summon Villager", "entity_villager"),
        new Effect("Summon Vex", "entity_vex"),
        new Effect("Summon Turtle", "entity_turtle"),
        new Effect("Summon Tropical Fish", "entity_tropical_fish"),
        new Effect("Summon Trader Llama", "entity_trader_llama"),
        new Effect("Summon Strider", "entity_strider"),
        new Effect("Summon Stray", "entity_stray"),
        new Effect("Summon Squid", "entity_squid"),
        new Effect("Summon Spider", "entity_spider"),
        new Effect("Summon Snow Golem", "entity_snowman"),
        new Effect("Summon Slime", "entity_slime"),
        new Effect("Summon Silverfish", "entity_silverfish"),
        new Effect("Summon Skeleton Horse", "entity_skeleton_horse"),
        new Effect("Summon Shulker", "entity_shulker"),
        new Effect("Summon Sheep", "entity_sheep"),
        new Effect("Summon Salmon", "entity_salmon"),
        new Effect("Summon Ravager", "entity_ravager"),
        new Effect("Summon Rabbit", "entity_rabbit"),
        new Effect("Summon Armor Stand", "entity_armor_stand"),
        new Effect("Summon Axolotl", "entity_axolotl"),
        new Effect("Summon Glow Squid", "entity_glow_squid"),
        new Effect("Summon Goat", "entity_goat"),
        // remove nearest entity
        new Effect("Remove Creeper", "remove_entity_creeper"),
        new Effect("Remove Skeleton", "remove_entity_skeleton"),
        new Effect("Remove Zombie", "remove_entity_zombie"),
        new Effect("Remove Zoglin", "remove_entity_zoglin"),
        new Effect("Remove Bat", "remove_entity_bat"),
        new Effect("Remove Bee", "remove_entity_bee"),
        new Effect("Remove Blaze", "remove_entity_blaze"),
        new Effect("Remove Boat", "remove_entity_boat"),
        new Effect("Remove Cat", "remove_entity_cat"),
        new Effect("Remove Cave Spider", "remove_entity_cave_spider"),
        new Effect("Remove Cod", "remove_entity_cod"),
        new Effect("Remove Cow", "remove_entity_cow"),
        new Effect("Remove Chicken", "remove_entity_chicken"),
        new Effect("Remove Dolphin", "remove_entity_dolphin"),
        new Effect("Remove Donkey", "remove_entity_donkey"),
        new Effect("Remove Drowned", "remove_entity_drowned"),
        new Effect("Remove Elder Guardian", "remove_entity_elder_guardian"),
        new Effect("Remove Enderman", "remove_entity_enderman"),
        new Effect("Remove Endermite", "remove_entity_endermite"),
        new Effect("Remove Evoker", "remove_entity_evoker"),
        new Effect("Remove Fox", "remove_entity_fox"),
        new Effect("Remove Ghast", "remove_entity_ghast"),
        new Effect("Remove Giant", "remove_entity_giant"),
        new Effect("Remove Guardian", "remove_entity_guardian"),
        new Effect("Remove Hoglin", "remove_entity_hoglin"),
        new Effect("Remove Horse", "remove_entity_horse"),
        new Effect("Remove Husk", "remove_entity_husk"),
        new Effect("Remove Lightning Bolt", "remove_entity_lightning"),
        new Effect("Remove Iron Golem", "remove_entity_iron_golem"),
        new Effect("Remove Illusioner", "remove_entity_illusioner"),
        new Effect("Remove Llama", "remove_entity_llama"),
        new Effect("Remove Magma Cube", "remove_entity_magma_cube"),
        new Effect("Remove Minecart", "remove_entity_minecart"),
        new Effect("Remove Minecart with Chest", "remove_entity_minecart_chest"),
        new Effect("Remove Minecart with Furnace", "remove_entity_minecart_furnace"),
        new Effect("Remove Minecart with Hopper", "remove_entity_minecart_hopper"),
        new Effect("Remove Minecart with TNT", "remove_entity_minecart_tnt"),
        new Effect("Remove Primed TNT", "remove_entity_primed_tnt"),
        new Effect("Remove Mule", "remove_entity_mule"),
        new Effect("Remove Mooshroom", "remove_entity_mushroom_cow"),
        new Effect("Remove Ocelot", "remove_entity_ocelot"),
        new Effect("Remove Panda", "remove_entity_panda"),
        new Effect("Remove Parrot", "remove_entity_parrot"),
        new Effect("Remove Phantom", "remove_entity_phantom"),
        new Effect("Remove Pig", "remove_entity_pig"),
        new Effect("Remove Piglin", "remove_entity_piglin"),
        new Effect("Remove Piglin Brute", "remove_entity_piglin_brute"),
        new Effect("Remove Pillager", "remove_entity_pillager"),
        new Effect("Remove Polar Bear", "remove_entity_polar_bear"),
        new Effect("Remove Pufferfish", "remove_entity_pufferfish"),
        new Effect("Remove Zombified Piglin", "remove_entity_zombified_piglin"),
        new Effect("Remove Zombie Horse", "remove_entity_zombie_horse"),
        new Effect("Remove Zombie Villager", "remove_entity_zombie_villager"),
        new Effect("Remove Wolf", "remove_entity_wolf"),
        new Effect("Remove Wither Skeleton", "remove_entity_wither_skeleton"),
        new Effect("Remove Wandering Trader", "remove_entity_wandering_trader"),
        new Effect("Remove Witch", "remove_entity_witch"),
        new Effect("Remove Vindicator", "remove_entity_vindicator"),
        new Effect("Remove Villager", "remove_entity_villager"),
        new Effect("Remove Vex", "remove_entity_vex"),
        new Effect("Remove Turtle", "remove_entity_turtle"),
        new Effect("Remove Tropical Fish", "remove_entity_tropical_fish"),
        new Effect("Remove Trader Llama", "remove_entity_trader_llama"),
        new Effect("Remove Strider", "remove_entity_strider"),
        new Effect("Remove Stray", "remove_entity_stray"),
        new Effect("Remove Squid", "remove_entity_squid"),
        new Effect("Remove Spider", "remove_entity_spider"),
        new Effect("Remove Snow Golem", "remove_entity_snowman"),
        new Effect("Remove Slime", "remove_entity_slime"),
        new Effect("Remove Silverfish", "remove_entity_silverfish"),
        new Effect("Remove Skeleton Horse", "remove_entity_skeleton_horse"),
        new Effect("Remove Shulker", "remove_entity_shulker"),
        new Effect("Remove Sheep", "remove_entity_sheep"),
        new Effect("Remove Salmon", "remove_entity_salmon"),
        new Effect("Remove Ravager", "remove_entity_ravager"),
        new Effect("Remove Rabbit", "remove_entity_rabbit"),
        new Effect("Remove Armor Stand", "remove_entity_armor_stand"),
        new Effect("Remove Axolotl", "remove_entity_axolotl"),
        new Effect("Remove Glow Squid", "remove_entity_glow_squid"),
        new Effect("Remove Goat", "remove_entity_goat"),
        // sets the server difficulty (affects how much damage mobs deal)
        new Effect("Set Difficulty: Peaceful", "difficulty_peaceful"),
        new Effect("Set Difficulty: Easy", "difficulty_easy"),
        new Effect("Set Difficulty: Normal", "difficulty_normal"),
        new Effect("Set Difficulty: Hard", "difficulty_hard"),
        // applies potion effects to every player
        new Effect("Apply Speed Potion Effect", "potion_speed"),
        new Effect("Apply Slowness Potion Effect", "potion_slowness"),
        new Effect("Apply Haste Potion Effect", "potion_haste"),
        new Effect("Apply Mining Fatigue Potion Effect", "potion_mining_fatigue"),
        new Effect("Apply Strength Potion Effect", "potion_strength"),
        new Effect("Apply Healing Potion Effect", "potion_healing"),
        new Effect("Apply Harming Potion Effect", "potion_harming"),
        new Effect("Apply Jump Boost Potion Effect", "potion_jump_boost"),
        new Effect("Apply Nausea Potion Effect", "potion_nausea"),
        new Effect("Apply Regeneration Potion Effect", "potion_regeneration"),
        new Effect("Apply Resistance Potion Effect", "potion_resistance"),
        new Effect("Apply Fire Resistance Potion Effect", "potion_fire_resistance"),
        new Effect("Apply Water Breathing Potion Effect", "potion_water_breathing"),
        new Effect("Apply Invisibility Potion Effect", "potion_invisibility"),
        new Effect("Apply Blindness Potion Effect", "potion_blindness"),
        new Effect("Apply Night Vision Potion Effect", "potion_night_vision"),
        new Effect("Apply Hunger Potion Effect", "potion_hunger"),
        new Effect("Apply Weakness Potion Effect", "potion_weakness"),
        new Effect("Apply Poison Potion Effect", "potion_poison"),
        new Effect("Apply Wither Potion Effect", "potion_wither"),
        new Effect("Apply Health Boost Potion Effect", "potion_health_boost"),
        new Effect("Apply Absorption Potion Effect", "potion_absorption"),
        new Effect("Apply Saturation Potion Effect", "potion_saturation"),
        new Effect("Apply Glowing Potion Effect", "potion_glowing"),
        new Effect("Apply Levitation Potion Effect", "potion_levitation"),
        new Effect("Apply Luck Potion Effect", "potion_luck"),
        new Effect("Apply Bad Luck Potion Effect", "potion_bad_luck"),
        new Effect("Apply Slow Falling Potion Effect", "potion_slow_falling"),
        new Effect("Apply Conduit Power Potion Effect", "potion_conduit_power"),
        new Effect("Apply Dolphins Grace Potion Effect", "potion_dolphins_grace"),
        new Effect("Apply Bad Omen Potion Effect", "potion_bad_omen"),
        new Effect("Apply Hero Of The Village Potion Effect", "potion_hero_of_the_village"),
        // places a block at everyone's feet
        new Effect("Place TNT Block", "block_tnt"),
        new Effect("Place Fire Block", "block_fire"),
        new Effect("Place Cobweb Block", "block_cobweb"),
        new Effect("Place Redstone Torch Block", "block_redstone_torch"),
        new Effect("Place Wither Rose Block", "block_wither_rose"),
        // places a block several blocks above everyone's head
        new Effect("Falling Anvil Block", "falling_block_anvil"),
        new Effect("Falling Sand Block", "falling_block_sand"),
        new Effect("Falling Red Sand Block", "falling_block_red_sand"),
        new Effect("Falling Gravel Block", "falling_block_gravel"),
        // sets the server weather
        new Effect("Set Weather to Downfall", "downfall"),
        new Effect("Set Weather to Clear", "clear"),
        // apply enchants
        new Effect("Remove Enchants", "remove_enchants"), // removes all enchants from the held item
        new Effect("Apply Fire Protection IV", "enchant_fire_protection"),
        new Effect("Apply Sharpness V", "enchant_sharpness"),
        new Effect("Apply Flame", "enchant_flame"),
        new Effect("Apply Soul Speed III", "enchant_soul_speed"),
        new Effect("Apply Aqua Affinity", "enchant_aqua_affinity"),
        new Effect("Apply Punch II", "enchant_punch"),
        new Effect("Apply Loyalty III", "enchant_loyalty"),
        new Effect("Apply Depth Strider III", "enchant_depth_strider"),
        new Effect("Apply Curse of Vanishing", "enchant_curse_of_vanishing"),
        new Effect("Apply Unbreaking III", "enchant_unbreaking"),
        new Effect("Apply Knockback II", "enchant_knockback"),
        new Effect("Apply Luck of the Sea III", "enchant_luck_of_the_sea"),
        new Effect("Apply Curse of Binding", "enchant_curse_of_binding"),
        new Effect("Apply Fortune III", "enchant_fortune"),
        new Effect("Apply Protection IV", "enchant_protection"),
        new Effect("Apply Efficiency V", "enchant_efficiency"),
        new Effect("Apply Mending", "enchant_mending"),
        new Effect("Apply Frost Walker II", "enchant_frost_walker"),
        new Effect("Apply Lure III", "enchant_lure"),
        new Effect("Apply Looting III", "enchant_looting"),
        new Effect("Apply Piercing IV", "enchant_piercing"),
        new Effect("Apply Blast Protection IV", "enchant_blast_protection"),
        new Effect("Apply Smite V", "enchant_smite"),
        new Effect("Apply Multishot", "enchant_multishot"),
        new Effect("Apply Fire Aspect II", "enchant_fire_aspect"),
        new Effect("Apply Channeling", "enchant_channeling"),
        new Effect("Apply Sweeping Edge III", "enchant_sweeping_edge"),
        new Effect("Apply Thorns III", "enchant_thorns"),
        new Effect("Apply Bane of Arthropods V", "enchant_bane_of_arthropods"),
        new Effect("Apply Respiration III", "enchant_respiration"),
        new Effect("Apply Riptide III", "enchant_riptide"),
        new Effect("Apply Silk Touch", "enchant_silk_touch"),
        new Effect("Apply Quick Charge III", "enchant_quick_charge"),
        new Effect("Apply Projectile Protection IV", "enchant_projectile_protection"),
        new Effect("Apply Impaling V", "enchant_impaling"),
        new Effect("Apply Feather Falling IV", "enchant_feather_falling"),
        new Effect("Apply Power V", "enchant_power"),
        new Effect("Apply Infinity", "enchant_infinity"),
        // gives/takes 1 item
        new Effect("Give Wooden Pickaxe", "give_wooden_pickaxe"),
        new Effect("Take Wooden Pickaxe", "take_wooden_pickaxe"),
        new Effect("Give Stone Pickaxe", "give_stone_pickaxe"),
        new Effect("Take Stone Pickaxe", "take_stone_pickaxe"),
        new Effect("Give Golden Pickaxe", "give_golden_pickaxe"),
        new Effect("Take Golden Pickaxe", "take_golden_pickaxe"),
        new Effect("Give Iron Pickaxe", "give_iron_pickaxe"),
        new Effect("Take Iron Pickaxe", "take_iron_pickaxe"),
        new Effect("Give Diamond Pickaxe", "give_diamond_pickaxe"),
        new Effect("Take Diamond Pickaxe", "take_diamond_pickaxe"),
        new Effect("Give Netherite Pickaxe", "give_netherite_pickaxe"),
        new Effect("Take Netherite Pickaxe", "take_netherite_pickaxe"),
        new Effect("Give Golden Apple", "give_golden_apple"),
        new Effect("Take Golden Apple", "take_golden_apple"),
        new Effect("Give Enchanted Golden Apple", "give_enchanted_golden_apple"),
        new Effect("Take Enchanted Golden Apple", "take_enchanted_golden_apple"),
    };
}