/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "minecraft-crowd-control"
include(":sponge8-platform")
include(":paper-platform")
include(":common-platform")
include(":sponge7-platform")
project(":sponge8-platform").projectDir = file("sponge-8")
project(":paper-platform").projectDir = file("paper")
project(":common-platform").projectDir = file("common")
project(":sponge7-platform").projectDir = file("sponge-7")
