# Password that Crowd Control clients must enter to connect to this Crowd Control server.
# A blank password will cause this plugin to operate in client mode, in which only one
#  streamer may connect to the CC server and all purchased effects will apply to everyone
#  on the Minecraft server.
password: ""

# IP address to connect to when running in client mode.
# This should usually be a local IP address (i.e. "127.0.0.1") unless this server is being
#  run on a different machine than the streamer's PC.
# This value is not applicable when running in server mode and thus will be ignored.
ip: 127.0.0.1

# Makes it so that all purchased effects apply to everyone on the server,
#  even when running in server-mode with individually connected clients.
# Enabling this is usually not recommended,
#  unless running in client-mode is not viable for your setup.
global: false

# The hosts or owners of a server, through which viewers are able to purchase specific universal
#  effects such as setting the server difficulty or changing the weather.
# Acceptable values for this field include Minecraft usernames,
#  UUIDs (formatted with or without dashes), Twitch usernames, and Twitch IDs.
# Example:
#hosts: ["MinecraftUsername1", "TwitchUsername2", "123456", "d1de9ca878f64aae87a18c112f675f12"]
hosts: []

# Determines whether to alert streamers in chat when an effect has been activated.
announce: true
