package dev.qixils.crowdcontrol.common;

import dev.qixils.crowdcontrol.common.custom.CustomCommandData;
import org.jetbrains.annotations.Nullable;
import org.spongepowered.configurate.objectmapping.ConfigSerializable;

import java.util.Collections;
import java.util.List;

/**
 * The configuration for custom effects.
 */
@ConfigSerializable
public record CustomEffectsConfig(boolean autogenerated, @Nullable List<CustomCommandData> effects) {
	public CustomEffectsConfig() {
		this(true, Collections.emptyList());
	}
}
