/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.qixils.crowdcontrol.plugin.java-conventions")
}

description = "Minecraft Crowd Control: Common"
