/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.qixils.crowdcontrol.plugin.java-conventions")
}

dependencies {
    implementation(project(":common-platform"))
    implementation("cloud.commandframework:cloud-sponge7:1.7.0-SNAPSHOT")
    implementation("net.kyori:adventure-platform-spongeapi:4.0.1")
    compileOnly("org.spongepowered:spongeapi:7.4.0")
}

description = "Minecraft Crowd Control: Sponge 7"
