/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.qixils.crowdcontrol.plugin.java-conventions")
}

dependencies {
    implementation(project(":common-platform"))
    implementation("cloud.commandframework:cloud-paper:1.7.0-SNAPSHOT")
    compileOnly("io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT")
}

description = "Minecraft Crowd Control: Paper"
