/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("dev.qixils.crowdcontrol.plugin.java-conventions")
}

dependencies {
    implementation(project(":common-platform"))
    implementation("cloud.commandframework:cloud-sponge:1.7.0-SNAPSHOT")
    compileOnly("org.spongepowered:spongeapi:8.0.0")
}

description = "Minecraft Crowd Control: Sponge 8"
